README.md
Signed-off-by: John Walicki <walicki@us.ibm.com>
=> Add Video Link to readme

server/routes/geospatial_definitions.test.js, server/routes/publications.test.js, server/routes/video_testimonials.test.js
Worked on CRUD integration testing for the video testimonials file in collaboration with @carrir2 https://github.com/carrir2. The tests passed and were based of categories.test.js. Thanks!
=> Update video testimonials test

server/routes/geospatial_definitions.test.js, server/routes/publications.test.js
Worked on CRUD integration testing for the publications file in collaboration with @carrir2 https://github.com/carrir2. The tests passed and were based of categories.test.js. Thanks!
=> Update publications integration testing

server/routes/advocacy_groups.test.js, server/routes/geospatial_definitions.test.js
Worked on CRUD integration testing for the advocacy_groups file in collaboration with @carrir2 https://github.com/carrir2. The tests passed and were based of categories.test.js. Thanks!
=> Update advocacy groups integration testing

server/routes/geospatial_definitions.test.js, server/routes/levels.test.js
Worked on CRUD integration testing for the levels file in collaboration with @carrir2 https://github.com/carrir2. The tests passed and were based of categories.test.js. Thanks!
=> Update levels integration testing

server/routes/geospatial_definitions.test.js, server/routes/legislative_artifacts.test.js, server/routes/publications.test.js, server/routes/video_testimonials.test.js
Worked on CRUD integration testing for the update legislative testimonials file in collaboration with @carrir2 https://github.com/carrir2. The tests passed and were based of categories.test.js. Thanks!
=> Update legislative artifacts tests

README.md
I expanded a little bit on how to deploy your own PostgreSQL instance locally on the download instructions.
=> Update README.md with more info on postgreSQL

server/admin/src/App.vue
Fixed the Truth Loop Admin UI Back to Home button. Fixes #114
=> Fixed the Truth Loop Admin UI Back to Home button.

client/src/components/AppTopBar/AppTopBar.vue, server/admin/src/App.vue
Update hover animation client fixes #105
=> Update hover animation client

client/src/components/AppTopBar/AppTopBar.vue, client/src/components/Policy/Policy.vue, server/admin/src/App.vue
Added hover effect for cursor on entire policy card instead of just summary in collaboration with @carrir2 https://github.com/carrir2.
Fixes #104
=> Update hover over policy

client/package.json, client/src/components/AppTopBar/AppTopBar.vue, client/src/components/Policy/Policy.vue, client/src/views/Record.vue, server/admin/src/App.vue
Added the ability to see yourself while recording a video submission for Truth Loop with @carrir2 https://github.com/carrir2.
Fixes #101
=> Update webcam while recording

client/.eslintrc.js, client/jest.config.js, client/package-lock.json, client/package.json, client/src/components/Policy/Policy.vue, client/tests/unit/components/AppTopBar.spec.js, client/tests/unit/components/AppTopBarTest.spec.js, client/tests/unit/components/Policy.spec.js
I am happy to generate more tests for this project but I wanted to make sure what I have so far is sufficient. 
Signed-off-by: ed.snodgrass <snodgrass.ed@gmail.com>
=> #96 Added AppTopBar component testing for title, hasSettings and hasBack

.gitignore, client/src/components/Policy/Policy.vue
Reverts Call-for-Code-for-Racial-Justice/Truth-Loop#122
The cursor pointer addition was already added, so this merge is a bit stale.  The end result was white space and deletion of the summary cursor pointer.  Since this PR is now older than the conflict that added the cursor pointer, I'm not sure I should accept the removal of the summary cursor pointer.  If that is still desirable how about a new PR or a rebase.
=> Revert "Issue #104-- Change hover animation to hover over entire policy rather than just summary portion."

README.md, react/client/src/fetchPolicy.js, react/client/src/fetchPolicy.test.js, react/client/src/store/index.js, react/client/src/store/reducers/policy.duck.js, react/client/src/store/reducers/policy.duck.test.js, react/client/src/store/reducers/privacy.duck.js, react/client/src/store/reducers/privacy.duck.test.js
This should be the last of the vuex -> redux transitions.
=> Policy and privacy ducks

react/client/src/fetchPolicy.js, react/client/src/fetchPolicy.test.js, react/client/src/mockdata/CURRENT_FULL_RETRIEVAL_OF_ARTIFACT_1.js, react/client/src/mockdata/CURRENT_LIST_RESULT.js, react/client/src/store/reducers/privacy.duck.js
I've fixed the issue Lucas found where the app couldn't retrieve the mock data. Also tweaked the privacy reducer where it was checking for null/undefined payload before checking action.type.
=> Fix fetch policy and privacy reducer

react/client/src/appTopBar/AppTopBar.js, react/client/src/appTopBar/AppTopBar.test.js, react/client/src/appTopBar/apptopbar.scss
Signed-off-by: felizj17 <felizj17@gmail.com>
=> added appTopBar react component and test file

react/client/src/App.js, react/client/src/appTopBar/AppTopBar.js, react/client/src/appTopBar/apptopbar.scss, react/client/src/filterMenu/FilterMenu.js, react/client/src/filterMenu/FilterMenu.test.js, react/client/src/filterMenu/filtermenu.scss
Signed-off-by: felizj17 <felizj17@gmail.com>
=> filter-menu added to the apptopbar(React)

react/client/package-lock.json, react/client/package.json, react/client/src/policyDetail/Sentiment.js, react/client/src/recordRoute/RecordRoute.js, react/client/src/recordRoute/RecordRoute.scss, react/client/src/recordRoute/RecordRoute.test.js
This fixes #157 . Unfortunately we don't have the ability to upload but we should probably create a new issue to implement
=> 157 react version of record

server/react-admin/src/artifacts/ArtifactForm.js, server/react-admin/src/artifacts/ArtifactIntersections.js, server/react-admin/src/artifacts/ArtifactTable.js, server/react-admin/src/artifacts/artifactIntersectionHeaders.js, server/react-admin/src/intersections/AddIntersectionsTable.js, server/react-admin/src/intersections/IntersectionsTable.js, server/react-admin/src/intersections/IntersectionsTable.test.js
closes #200 
Added ability to add/delete artifact intersections
To help finish out the react version of the admin application.
Some unit tests updated. went through and added/deleted different intersections.
=> 200 react admin intersections

server/react-admin/package-lock.json, server/react-admin/package.json, server/react-admin/src/AdminApp.js, server/react-admin/src/adminHomeRoute/AdminHomeRoute.js, server/react-admin/src/adminapp.scss, server/react-admin/src/sidemenu/SideNav.js
Signed-off-by: Ed Snodgrass <snodgrass.ed@gmail.com>
Contributes to # (add issue number here. i.e. `#302`)
Added a home view with a hero image with text overlayed.
Last piece of React Admin.
Loaded the page
=> #197 Updated the Home view to look like the vue version.
